server.port=8080

# Redis
spring.data.redis.host=${REDIS_HOST:127.0.0.1}
spring.data.redis.port=${REDIS_PORT:6379}

# Token Bucket
rate-limiter.bucket-capacity=${RATE_LIMIT_CAPACITY:10}
rate-limiter.refill-rate=${RATE_LIMIT_REFILL_RATE:2.0}
rate-limiter.idle-ttl-seconds=${RATE_LIMIT_IDLE_TTL:86400}

# OpenAPI / Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html