services:
  configsvr:
    image: mongo:7.0
    command: mongod --configsvr --replSet configrs --port 27017 --dbpath /data/db
    ports:
      - 27019:27017
    volumes:
      - ./data/configsvr:/data/db
      - ./scripts:/scripts
    networks:
      - shard-net

  shard1:
    image: mongo:7.0
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports:
      - 27020:27017
    volumes:
      - ./data/shard1:/data/db
      - ./scripts:/scripts
    networks:
      - shard-net

  shard2:
    image: mongo:7.0
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 27021:27017
    volumes:
      - ./data/shard2:/data/db
      - ./scripts:/scripts
    networks:
      - shard-net

  mongos:
    image: mongo:7.0
    command: mongos --configdb configrs/configsvr:27017 --port 27017 --bind_ip_all
    ports:
      - 27017:27017
    volumes:
      - ./scripts:/scripts
    depends_on:
      - configsvr
      - shard1
      - shard2
    networks:
      - shard-net

  mongo-express:
    image: mongo-express:1.0
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongos:27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_SITE_COOKIESECRET: shard-secret
      ME_CONFIG_SITE_SESSIONSECRET: shard-secret
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongos
    networks:
      - shard-net

  mongo-express-shard1:
    image: mongo-express:1.0
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://shard1:27017/?directConnection=true
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_SITE_COOKIESECRET: shard-secret
      ME_CONFIG_SITE_SESSIONSECRET: shard-secret
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - shard1
    networks:
      - shard-net

  mongo-express-shard2:
    image: mongo-express:1.0
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://shard2:27017/?directConnection=true
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_SITE_COOKIESECRET: shard-secret
      ME_CONFIG_SITE_SESSIONSECRET: shard-secret
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - shard2
    networks:
      - shard-net

networks:
  shard-net:
    driver: bridge