server.port=${PORT:8080}

# Initial storage nodes (host:port in Docker network "shard-net")
app.nodes=mongo1:27017,mongo2:27018,mongo3:27019

# Consistent hashing
app.virtual-nodes=150

# OpenAPI / Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Logging
logging.level.com.consistenthashing=INFO
logging.level.org.mongodb.driver=INFO
